import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/demos">Demos</Link>
        <h1>This is the main HOME PAGE</h1>
        <p>
          I am a highly skilled developer with extensive experience in Next.js
          and Firebase. I can help you troubleshoot the 500 error you are
          encountering with your dynamic route when deployed
        </p>
      </main>
    </>
  );
}
